name: Build and deploy to gh-pages

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Use Node.js v16
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: "16.x"
            - name: Install dependencies
              run: npm ci
            - name: Add basepath to next configuration
              run: |
                  sed -i '12ibasePath: "/next-js-mui-pwa-starter",' next.config.js
            - name: Build site
              run: npm run build-static
            - name: Add nojekyll file
              run: |
                  cd out/
                  touch .nojekyll
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  branch: gh-pages
                  folder: out
