name: Build and deploy to gh-pages

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Use Node.js v16
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Install dependencies
              run: npm ci
            - name: Build site
              run: npm run build-static
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  branch: gh-pages
                  folder: out
