name: Build and deploy to gh-pages

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 6.32.3
            - name: Use Node.js v16
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Add basepath to next configuration
              run: |
                  sed -i '9ibasePath: "/next-js-mui-pwa-starter",' next.config.js
            - name: Build site
              run: npm run build-static
            - name: Add nojekyll file
              run: |
                  cd out/
                  touch .nojekyll
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: out
